export enum LevellingType {
  Experience = 'Experience',
  Milestone = 'Milestone',
}

export enum CharacterClass {
  Artificer = 'Artificer',
  Barbarian = 'Barbarian',
  Bard = 'Bard',
  BloodHunter = 'Blood Hunter',
  Cleric = 'Cleric',
  Druid = 'Druid',
  Fighter = 'Fighter',
  Monk = 'Monk',
  Paladin = 'Paladin',
  Ranger = 'Ranger',
  Rogue = 'Rogue',
  Sorcerer = 'Sorcerer',
  Warlock = 'Warlock',
  Wizard = 'Wizard',
}

export enum CharacterRace {
  Aarakocra = 'Aarakocra',
  Aasimar = 'Aasimar',
  Bugbear = 'Bugbear',
  Dragonborn = 'Dragonborn',
  Dwarf = 'Dwarf',
  Elf = 'Elf',
  Firbolg = 'Firbolg',
  Gnome = 'Gnome',
  Goblin = 'Goblin',
  Goliath = 'Goliath',
  HalfElf = 'Half-Elf',
  HalfOrc = 'Half-Orc',
  Halfling = 'Halfling',
  Hobgoblin = 'Hobgoblin',
  Human = 'Human',
  Tiefling = 'Tiefling',
  Tortle = 'Tortle',
  YuanTi = 'Yuan-Ti',
  AirGenasi = 'Air Genasi',
  EarthGenasi = 'Earth Genasi',
  Centaur = 'Centaur',
  Changeling = 'Changeling',
  DeepGnome = 'Deep Gnome',
  Duergar = 'Duergar',
  Eladrin = 'Eladrin',
  Fairy = 'Fairy',
  FireGenasi = 'Fire Genasi',
  Githyanki = 'Githyanki',
  Githzerai = 'Githzerai',
  Harengon = 'Harengon',
  Kenku = 'Kenku',
  Kobold = 'Kobold',
  Lizardfolk = 'Lizardfolk',
  Minotaur = 'Minotaur',
  Orc = 'Orc',
  Satyr = 'Satyr',
  SeaElf = 'Sea Elf',
  Shadarkai = 'Shadar-kai',
  Shifter = 'Shifter',
  Tabaxi = 'Tabaxi',
  Triton = 'Triton',
  Warforged = 'Warforged',
  WaterGenasi = 'Water Genasi',
  Kender = 'Kender',
  AstralElf = 'Astral Elf',
  Autognome = 'Autognome',
  Giff = 'Giff',
  Hadozee = 'Hadozee',
  Plasmoid = 'Plasmoid',
  ThriKreen = 'Thri-Kreen',
  Owlin = 'Owlin',
  Leonin = 'Leonin',
  Kalashtar = 'Kalashtar',
  Verdan = 'Verdan',
  Loxodon = 'Loxodon',
  SimicHybrid = 'Simic Hybrid',
  Vedalken = 'Vedalken',
  FeralTiefling = 'Feral Tiefling',
  Locathah = 'Locathah',
  Grung = 'Grung',
  Gith = 'Gith',
}

export enum SkillProficiencyLevel {
  None = 'None',
  Proficient = 'Proficient',
  Expert = 'Expert',
}

export enum AbilityType {
  Strength = 'strength',
  Dexterity = 'dexterity',
  Constitution = 'constitution',
  Intelligence = 'intelligence',
  Wisdom = 'wisdom',
  Charisma = 'charisma',
}

export enum CooldownPeriods {
  ShortRest = 'Short Rest',
  LongRest = 'Long Rest',
  Day = 'Day',
}
